//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18063.
// 
#pragma warning disable 1591

namespace CopRevenueGov2.RTTIE022_SrvRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TIPSACCTSOAP11Binding", Namespace="http://namespace.softwareag.com/entirex/xml/mapping")]
    public partial class TT022E00 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CallTT022E00OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TT022E00() {
            this.Url = "http://192.168.204.70:10010/wsstack/services/TT022E00.TIPSACCTSOAP11Port/";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallTT022E00CompletedEventHandler CallTT022E00Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TT022E00", RequestElementName="TT022E00", RequestNamespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT022E00", ResponseElementName="TT022E00Response", ResponseNamespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT022E00", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("_SMA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TT022E00Response_SMA CallTT022E00([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] TT022E00_SMA _SMA, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] TT022E00_EMI _EMI, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] TT022E00_ETA _ETA, [System.Xml.Serialization.XmlElementAttribute("_EMI", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out TT022E00Response_EMI _EMI1, [System.Xml.Serialization.XmlElementAttribute("_ETA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out TT022E00Response_ETA _ETA1) {
            object[] results = this.Invoke("CallTT022E00", new object[] {
                        _SMA,
                        _EMI,
                        _ETA});
            _EMI1 = ((TT022E00Response_EMI)(results[1]));
            _ETA1 = ((TT022E00Response_ETA)(results[2]));
            return ((TT022E00Response_SMA)(results[0]));
        }
        
        /// <remarks/>
        public void CallTT022E00Async(TT022E00_SMA _SMA, TT022E00_EMI _EMI, TT022E00_ETA _ETA) {
            this.CallTT022E00Async(_SMA, _EMI, _ETA, null);
        }
        
        /// <remarks/>
        public void CallTT022E00Async(TT022E00_SMA _SMA, TT022E00_EMI _EMI, TT022E00_ETA _ETA, object userState) {
            if ((this.CallTT022E00OperationCompleted == null)) {
                this.CallTT022E00OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallTT022E00OperationCompleted);
            }
            this.InvokeAsync("CallTT022E00", new object[] {
                        _SMA,
                        _EMI,
                        _ETA}, this.CallTT022E00OperationCompleted, userState);
        }
        
        private void OnCallTT022E00OperationCompleted(object arg) {
            if ((this.CallTT022E00Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallTT022E00Completed(this, new CallTT022E00CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT022E00")]
    public partial class TT022E00_SMA {
        
        private TT022E00_SMA_SYSTEMMESSAGEAREA _SYSTEMMESSAGEAREAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_SYSTEM-MESSAGE-AREA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TT022E00_SMA_SYSTEMMESSAGEAREA _SYSTEMMESSAGEAREA {
            get {
                return this._SYSTEMMESSAGEAREAField;
            }
            set {
                this._SYSTEMMESSAGEAREAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT022E00")]
    public partial class TT022E00_SMA_SYSTEMMESSAGEAREA {
        
        private string _PROGRAMField;
        
        private decimal eRRORField;
        
        private bool eRRORFieldSpecified;
        
        private decimal lINEField;
        
        private bool lINEFieldSpecified;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _PROGRAM {
            get {
                return this._PROGRAMField;
            }
            set {
                this._PROGRAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ERROR {
            get {
                return this.eRRORField;
            }
            set {
                this.eRRORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ERRORSpecified {
            get {
                return this.eRRORFieldSpecified;
            }
            set {
                this.eRRORFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal LINE {
            get {
                return this.lINEField;
            }
            set {
                this.lINEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LINESpecified {
            get {
                return this.lINEFieldSpecified;
            }
            set {
                this.lINEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT022E00")]
    public partial class TT022E00_EMI {
        
        private TT022E00_EMI_ENTITYMASTERINFO _ENTITYMASTERINFOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_ENTITY-MASTER-INFO", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TT022E00_EMI_ENTITYMASTERINFO _ENTITYMASTERINFO {
            get {
                return this._ENTITYMASTERINFOField;
            }
            set {
                this._ENTITYMASTERINFOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT022E00")]
    public partial class TT022E00_EMI_ENTITYMASTERINFO {
        
        private decimal eNTITYTYPEField;
        
        private bool eNTITYTYPEFieldSpecified;
        
        private string eNTITYIDField;
        
        private string fUNCTIONField;
        
        private string nOTICENUMField;
        
        private string nEXTACCOUNTField;
        
        private string nEXTACCOUNTIDField;
        
        private string nEXTPERIODField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ENTITYTYPE {
            get {
                return this.eNTITYTYPEField;
            }
            set {
                this.eNTITYTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ENTITYTYPESpecified {
            get {
                return this.eNTITYTYPEFieldSpecified;
            }
            set {
                this.eNTITYTYPEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENTITYID {
            get {
                return this.eNTITYIDField;
            }
            set {
                this.eNTITYIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FUNCTION {
            get {
                return this.fUNCTIONField;
            }
            set {
                this.fUNCTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NOTICE-NUM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NOTICENUM {
            get {
                return this.nOTICENUMField;
            }
            set {
                this.nOTICENUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NEXT-ACCOUNT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NEXTACCOUNT {
            get {
                return this.nEXTACCOUNTField;
            }
            set {
                this.nEXTACCOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NEXT-ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NEXTACCOUNTID {
            get {
                return this.nEXTACCOUNTIDField;
            }
            set {
                this.nEXTACCOUNTIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NEXT-PERIOD", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NEXTPERIOD {
            get {
                return this.nEXTPERIODField;
            }
            set {
                this.nEXTPERIODField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT022E00")]
    public partial class TT022E00_ETA {
        
        private TT022E00_ETA_ENTITYTAXACCOUNTS[] _ENTITYTAXACCOUNTSsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("_ENTITY-TAX-ACCOUNTSs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_ENTITY-TAX-ACCOUNTS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public TT022E00_ETA_ENTITYTAXACCOUNTS[] _ENTITYTAXACCOUNTSs {
            get {
                return this._ENTITYTAXACCOUNTSsField;
            }
            set {
                this._ENTITYTAXACCOUNTSsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT022E00")]
    public partial class TT022E00_ETA_ENTITYTAXACCOUNTS {
        
        private string fUNCTIONCODEField;
        
        private string aCCOUNTField;
        
        private string aCCOUNTIDField;
        
        private string pERIODXField;
        
        private string pRINCIPALXField;
        
        private string iNTERESTXField;
        
        private string pENALTYXField;
        
        private string oTHERXField;
        
        private string bRTENTITYField;
        
        private string bRTADDRESSField;
        
        private string fILLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FUNCTION-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FUNCTIONCODE {
            get {
                return this.fUNCTIONCODEField;
            }
            set {
                this.fUNCTIONCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNT {
            get {
                return this.aCCOUNTField;
            }
            set {
                this.aCCOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PERIOD-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERIODX {
            get {
                return this.pERIODXField;
            }
            set {
                this.pERIODXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PRINCIPAL-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRINCIPALX {
            get {
                return this.pRINCIPALXField;
            }
            set {
                this.pRINCIPALXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("INTEREST-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTERESTX {
            get {
                return this.iNTERESTXField;
            }
            set {
                this.iNTERESTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PENALTY-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PENALTYX {
            get {
                return this.pENALTYXField;
            }
            set {
                this.pENALTYXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OTHER-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OTHERX {
            get {
                return this.oTHERXField;
            }
            set {
                this.oTHERXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BRT-ENTITY", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRTENTITY {
            get {
                return this.bRTENTITYField;
            }
            set {
                this.bRTENTITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BRT-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRTADDRESS {
            get {
                return this.bRTADDRESSField;
            }
            set {
                this.bRTADDRESSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FILL {
            get {
                return this.fILLField;
            }
            set {
                this.fILLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT022E00")]
    public partial class TT022E00Response_SMA {
        
        private TT022E00Response_SMA_SYSTEMMESSAGEAREA _SYSTEMMESSAGEAREAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_SYSTEM-MESSAGE-AREA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TT022E00Response_SMA_SYSTEMMESSAGEAREA _SYSTEMMESSAGEAREA {
            get {
                return this._SYSTEMMESSAGEAREAField;
            }
            set {
                this._SYSTEMMESSAGEAREAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT022E00")]
    public partial class TT022E00Response_SMA_SYSTEMMESSAGEAREA {
        
        private string _PROGRAMField;
        
        private decimal eRRORField;
        
        private bool eRRORFieldSpecified;
        
        private decimal lINEField;
        
        private bool lINEFieldSpecified;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _PROGRAM {
            get {
                return this._PROGRAMField;
            }
            set {
                this._PROGRAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ERROR {
            get {
                return this.eRRORField;
            }
            set {
                this.eRRORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ERRORSpecified {
            get {
                return this.eRRORFieldSpecified;
            }
            set {
                this.eRRORFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal LINE {
            get {
                return this.lINEField;
            }
            set {
                this.lINEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LINESpecified {
            get {
                return this.lINEFieldSpecified;
            }
            set {
                this.lINEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT022E00")]
    public partial class TT022E00Response_EMI {
        
        private TT022E00Response_EMI_ENTITYMASTERINFO _ENTITYMASTERINFOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_ENTITY-MASTER-INFO", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TT022E00Response_EMI_ENTITYMASTERINFO _ENTITYMASTERINFO {
            get {
                return this._ENTITYMASTERINFOField;
            }
            set {
                this._ENTITYMASTERINFOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT022E00")]
    public partial class TT022E00Response_EMI_ENTITYMASTERINFO {
        
        private decimal eNTITYTYPEField;
        
        private bool eNTITYTYPEFieldSpecified;
        
        private string eNTITYIDField;
        
        private string fUNCTIONField;
        
        private string nOTICENUMField;
        
        private string nEXTACCOUNTField;
        
        private string nEXTACCOUNTIDField;
        
        private string nEXTPERIODField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ENTITYTYPE {
            get {
                return this.eNTITYTYPEField;
            }
            set {
                this.eNTITYTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ENTITYTYPESpecified {
            get {
                return this.eNTITYTYPEFieldSpecified;
            }
            set {
                this.eNTITYTYPEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENTITYID {
            get {
                return this.eNTITYIDField;
            }
            set {
                this.eNTITYIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FUNCTION {
            get {
                return this.fUNCTIONField;
            }
            set {
                this.fUNCTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NOTICE-NUM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NOTICENUM {
            get {
                return this.nOTICENUMField;
            }
            set {
                this.nOTICENUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NEXT-ACCOUNT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NEXTACCOUNT {
            get {
                return this.nEXTACCOUNTField;
            }
            set {
                this.nEXTACCOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NEXT-ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NEXTACCOUNTID {
            get {
                return this.nEXTACCOUNTIDField;
            }
            set {
                this.nEXTACCOUNTIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NEXT-PERIOD", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NEXTPERIOD {
            get {
                return this.nEXTPERIODField;
            }
            set {
                this.nEXTPERIODField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT022E00")]
    public partial class TT022E00Response_ETA {
        
        private TT022E00Response_ETA_ENTITYTAXACCOUNTS[] _ENTITYTAXACCOUNTSsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("_ENTITY-TAX-ACCOUNTSs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_ENTITY-TAX-ACCOUNTS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public TT022E00Response_ETA_ENTITYTAXACCOUNTS[] _ENTITYTAXACCOUNTSs {
            get {
                return this._ENTITYTAXACCOUNTSsField;
            }
            set {
                this._ENTITYTAXACCOUNTSsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT022E00")]
    public partial class TT022E00Response_ETA_ENTITYTAXACCOUNTS {
        
        private string fUNCTIONCODEField;
        
        private string aCCOUNTField;
        
        private string aCCOUNTIDField;
        
        private string pERIODXField;
        
        private string pRINCIPALXField;
        
        private string iNTERESTXField;
        
        private string pENALTYXField;
        
        private string oTHERXField;
        
        private string bRTENTITYField;
        
        private string bRTADDRESSField;
        
        private string fILLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FUNCTION-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FUNCTIONCODE {
            get {
                return this.fUNCTIONCODEField;
            }
            set {
                this.fUNCTIONCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNT {
            get {
                return this.aCCOUNTField;
            }
            set {
                this.aCCOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PERIOD-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERIODX {
            get {
                return this.pERIODXField;
            }
            set {
                this.pERIODXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PRINCIPAL-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRINCIPALX {
            get {
                return this.pRINCIPALXField;
            }
            set {
                this.pRINCIPALXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("INTEREST-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTERESTX {
            get {
                return this.iNTERESTXField;
            }
            set {
                this.iNTERESTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PENALTY-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PENALTYX {
            get {
                return this.pENALTYXField;
            }
            set {
                this.pENALTYXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OTHER-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OTHERX {
            get {
                return this.oTHERXField;
            }
            set {
                this.oTHERXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BRT-ENTITY", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRTENTITY {
            get {
                return this.bRTENTITYField;
            }
            set {
                this.bRTENTITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BRT-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRTADDRESS {
            get {
                return this.bRTADDRESSField;
            }
            set {
                this.bRTADDRESSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FILL {
            get {
                return this.fILLField;
            }
            set {
                this.fILLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CallTT022E00CompletedEventHandler(object sender, CallTT022E00CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallTT022E00CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallTT022E00CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TT022E00Response_SMA Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TT022E00Response_SMA)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TT022E00Response_EMI _EMI1 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TT022E00Response_EMI)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public TT022E00Response_ETA _ETA1 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TT022E00Response_ETA)(this.results[2]));
            }
        }
    }
}

#pragma warning restore 1591