//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopRevenueGov2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://192.168.204.70:10011/wsstack/services/TT010E00.TT010E00HttpsSoap12Endpoin" +
            "t/")]
        public string CopRevenueGov2_RTTIE010_SrvRef_TT010E00 {
            get {
                return ((string)(this["CopRevenueGov2_RTTIE010_SrvRef_TT010E00"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.204.70:10010/wsstack/services/TT037E00.TIPSACCTSOAP12Port/")]
        public string CopRevenueGov2_BPTLFEZ_RT01E037_SrvRef_TT037E00 {
            get {
                return ((string)(this["CopRevenueGov2_BPTLFEZ_RT01E037_SrvRef_TT037E00"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://192.168.204.70:10011/wsstack/services/TT031E00.TT031E00HttpsSoap11Endpoin" +
            "t/")]
        public string CopRevenueGov2_LCF_RTTIE031_SrvRef_TT031E00 {
            get {
                return ((string)(this["CopRevenueGov2_LCF_RTTIE031_SrvRef_TT031E00"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://192.168.204.70:10011/wsstack/services/TT016E00.TT016E00HttpsSoap11Endpoin" +
            "t/")]
        public string CopRevenueGov2_RTTIE016_SrvRef_TT016E00 {
            get {
                return ((string)(this["CopRevenueGov2_RTTIE016_SrvRef_TT016E00"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://192.168.204.70:10011/wsstack/services/TT022E00.TT022E00HttpsSoap11Endpoin" +
            "t/")]
        public string CopRevenueGov2_RTTIE022_SrvRef_TT022E00 {
            get {
                return ((string)(this["CopRevenueGov2_RTTIE022_SrvRef_TT022E00"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.204.70:10010/wsstack/services/TT030E00.TIPSACCTSOAP12Port/")]
        public string CopRevenueGov2_RTTIE030_SrvRef_TT030E00 {
            get {
                return ((string)(this["CopRevenueGov2_RTTIE030_SrvRef_TT030E00"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.204.70:10010/wsstack/services/TT040E00.TIPSACCTSOAP12Port/")]
        public string CopRevenueGov2_RTTIE040_SrvRef_TT040E00 {
            get {
                return ((string)(this["CopRevenueGov2_RTTIE040_SrvRef_TT040E00"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.204.70:10010/wsstack/services/TT036E00.TIPSACCTSOAP12Port/")]
        public string CopRevenueGov2_SIT_RTTIE036_SrvRef_TT036E00 {
            get {
                return ((string)(this["CopRevenueGov2_SIT_RTTIE036_SrvRef_TT036E00"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://192.168.204.70:10011/wsstack/services/TT028E00.TT028E00HttpsSoap11Endpoin" +
            "t/")]
        public string CopRevenueGov2_TOBACCO_RTTIE028_SrvRef_TT028E00 {
            get {
                return ((string)(this["CopRevenueGov2_TOBACCO_RTTIE028_SrvRef_TT028E00"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.204.70:10010/wsstack/services/TT035E00.TIPSACCTSOAP12Port/")]
        public string CopRevenueGov2_UOForm_RTTIE035_SrvRef_TT035E00 {
            get {
                return ((string)(this["CopRevenueGov2_UOForm_RTTIE035_SrvRef_TT035E00"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.204.70:10010/wsstack/services/TT034E00.TIPSACCTSOAP12Port/")]
        public string CopRevenueGov2_UOList_RTTIE034_SrvRef_TT034E00 {
            get {
                return ((string)(this["CopRevenueGov2_UOList_RTTIE034_SrvRef_TT034E00"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.204.70:10010/wsstack/services/TT027E00.TIPSACCTSOAP12Port/")]
        public string CopRevenueGov2_WAGE_RTTIE027_SrvRef_TT027E00 {
            get {
                return ((string)(this["CopRevenueGov2_WAGE_RTTIE027_SrvRef_TT027E00"]));
            }
        }
    }
}
