//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18063.
// 
#pragma warning disable 1591

namespace CopRevenueGov2.RTTIE016_SrvRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TIPSACCTSOAP11Binding", Namespace="http://namespace.softwareag.com/entirex/xml/mapping")]
    public partial class TT016E00 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CallTT016E00OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TT016E00() {
            this.Url = "http://192.168.204.70:10010/wsstack/services/TT016E00.TIPSACCTSOAP11Port/";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallTT016E00CompletedEventHandler CallTT016E00Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TT016E00", RequestElementName="TT016E00", RequestNamespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT016E00", ResponseElementName="TT016E00Response", ResponseNamespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT016E00", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("_SMA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TT016E00Response_SMA CallTT016E00([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] TT016E00_SMA _SMA, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] TT016E00_EMI _EMI, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] TT016E00_ETA _ETA, [System.Xml.Serialization.XmlElementAttribute("_E-WAG-NTL", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] TT016E00_EWAGNTL _EWAGNTL, [System.Xml.Serialization.XmlElementAttribute("_EMI", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out TT016E00Response_EMI _EMI1, [System.Xml.Serialization.XmlElementAttribute("_ETA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out TT016E00Response_ETA _ETA1, [System.Xml.Serialization.XmlElementAttribute("_E-WAG-NTL", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out TT016E00Response_EWAGNTL _EWAGNTL1) {
            object[] results = this.Invoke("CallTT016E00", new object[] {
                        _SMA,
                        _EMI,
                        _ETA,
                        _EWAGNTL});
            _EMI1 = ((TT016E00Response_EMI)(results[1]));
            _ETA1 = ((TT016E00Response_ETA)(results[2]));
            _EWAGNTL1 = ((TT016E00Response_EWAGNTL)(results[3]));
            return ((TT016E00Response_SMA)(results[0]));
        }
        
        /// <remarks/>
        public void CallTT016E00Async(TT016E00_SMA _SMA, TT016E00_EMI _EMI, TT016E00_ETA _ETA, TT016E00_EWAGNTL _EWAGNTL) {
            this.CallTT016E00Async(_SMA, _EMI, _ETA, _EWAGNTL, null);
        }
        
        /// <remarks/>
        public void CallTT016E00Async(TT016E00_SMA _SMA, TT016E00_EMI _EMI, TT016E00_ETA _ETA, TT016E00_EWAGNTL _EWAGNTL, object userState) {
            if ((this.CallTT016E00OperationCompleted == null)) {
                this.CallTT016E00OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallTT016E00OperationCompleted);
            }
            this.InvokeAsync("CallTT016E00", new object[] {
                        _SMA,
                        _EMI,
                        _ETA,
                        _EWAGNTL}, this.CallTT016E00OperationCompleted, userState);
        }
        
        private void OnCallTT016E00OperationCompleted(object arg) {
            if ((this.CallTT016E00Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallTT016E00Completed(this, new CallTT016E00CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT016E00")]
    public partial class TT016E00_SMA {
        
        private TT016E00_SMA_SYSTEMMESSAGEAREA _SYSTEMMESSAGEAREAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_SYSTEM-MESSAGE-AREA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TT016E00_SMA_SYSTEMMESSAGEAREA _SYSTEMMESSAGEAREA {
            get {
                return this._SYSTEMMESSAGEAREAField;
            }
            set {
                this._SYSTEMMESSAGEAREAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT016E00")]
    public partial class TT016E00_SMA_SYSTEMMESSAGEAREA {
        
        private string _PROGRAMField;
        
        private decimal eRRORField;
        
        private bool eRRORFieldSpecified;
        
        private decimal lINEField;
        
        private bool lINEFieldSpecified;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _PROGRAM {
            get {
                return this._PROGRAMField;
            }
            set {
                this._PROGRAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ERROR {
            get {
                return this.eRRORField;
            }
            set {
                this.eRRORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ERRORSpecified {
            get {
                return this.eRRORFieldSpecified;
            }
            set {
                this.eRRORFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal LINE {
            get {
                return this.lINEField;
            }
            set {
                this.lINEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LINESpecified {
            get {
                return this.lINEFieldSpecified;
            }
            set {
                this.lINEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT016E00")]
    public partial class TT016E00_EMI {
        
        private TT016E00_EMI_ENTITYMASTERINFO _ENTITYMASTERINFOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_ENTITY-MASTER-INFO", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TT016E00_EMI_ENTITYMASTERINFO _ENTITYMASTERINFO {
            get {
                return this._ENTITYMASTERINFOField;
            }
            set {
                this._ENTITYMASTERINFOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT016E00")]
    public partial class TT016E00_EMI_ENTITYMASTERINFO {
        
        private string fUNCTIONCODEField;
        
        private decimal eNTITYTYPEField;
        
        private bool eNTITYTYPEFieldSpecified;
        
        private string eNTITYIDField;
        
        private string aCCTIDField;
        
        private string eNTITYNAMEField;
        
        private string aDDRESSLINEField;
        
        private string aDDRESSLINE2Field;
        
        private string aDDRESSLINE3Field;
        
        private string cITYField;
        
        private string sTATEField;
        
        private string zIPCODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FUNCTION-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FUNCTIONCODE {
            get {
                return this.fUNCTIONCODEField;
            }
            set {
                this.fUNCTIONCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ENTITYTYPE {
            get {
                return this.eNTITYTYPEField;
            }
            set {
                this.eNTITYTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ENTITYTYPESpecified {
            get {
                return this.eNTITYTYPEFieldSpecified;
            }
            set {
                this.eNTITYTYPEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENTITYID {
            get {
                return this.eNTITYIDField;
            }
            set {
                this.eNTITYIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCTID {
            get {
                return this.aCCTIDField;
            }
            set {
                this.aCCTIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-NAME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENTITYNAME {
            get {
                return this.eNTITYNAMEField;
            }
            set {
                this.eNTITYNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADDRESS-LINE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADDRESSLINE {
            get {
                return this.aDDRESSLINEField;
            }
            set {
                this.aDDRESSLINEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADDRESS-LINE-2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADDRESSLINE2 {
            get {
                return this.aDDRESSLINE2Field;
            }
            set {
                this.aDDRESSLINE2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADDRESS-LINE-3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADDRESSLINE3 {
            get {
                return this.aDDRESSLINE3Field;
            }
            set {
                this.aDDRESSLINE3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CITY {
            get {
                return this.cITYField;
            }
            set {
                this.cITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STATE {
            get {
                return this.sTATEField;
            }
            set {
                this.sTATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ZIP-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZIPCODE {
            get {
                return this.zIPCODEField;
            }
            set {
                this.zIPCODEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT016E00")]
    public partial class TT016E00_ETA {
        
        private TT016E00_ETA_ENTITYTAXACCOUNTS[] _ENTITYTAXACCOUNTSsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("_ENTITY-TAX-ACCOUNTSs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_ENTITY-TAX-ACCOUNTS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public TT016E00_ETA_ENTITYTAXACCOUNTS[] _ENTITYTAXACCOUNTSs {
            get {
                return this._ENTITYTAXACCOUNTSsField;
            }
            set {
                this._ENTITYTAXACCOUNTSsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT016E00")]
    public partial class TT016E00_ETA_ENTITYTAXACCOUNTS {
        
        private string fUNCTIONCODEField;
        
        private decimal aCCOUNTField;
        
        private bool aCCOUNTFieldSpecified;
        
        private string aCCOUNTIDField;
        
        private decimal sTARTDATEField;
        
        private bool sTARTDATEFieldSpecified;
        
        private decimal eNDDATEField;
        
        private bool eNDDATEFieldSpecified;
        
        private string fREQUENCYField;
        
        private string bRTENTITYField;
        
        private string bRTADDRESSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FUNCTION-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FUNCTIONCODE {
            get {
                return this.fUNCTIONCODEField;
            }
            set {
                this.fUNCTIONCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ACCOUNT {
            get {
                return this.aCCOUNTField;
            }
            set {
                this.aCCOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ACCOUNTSpecified {
            get {
                return this.aCCOUNTFieldSpecified;
            }
            set {
                this.aCCOUNTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("START-DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal STARTDATE {
            get {
                return this.sTARTDATEField;
            }
            set {
                this.sTARTDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool STARTDATESpecified {
            get {
                return this.sTARTDATEFieldSpecified;
            }
            set {
                this.sTARTDATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("END-DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ENDDATE {
            get {
                return this.eNDDATEField;
            }
            set {
                this.eNDDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ENDDATESpecified {
            get {
                return this.eNDDATEFieldSpecified;
            }
            set {
                this.eNDDATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FREQUENCY {
            get {
                return this.fREQUENCYField;
            }
            set {
                this.fREQUENCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BRT-ENTITY", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRTENTITY {
            get {
                return this.bRTENTITYField;
            }
            set {
                this.bRTENTITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BRT-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRTADDRESS {
            get {
                return this.bRTADDRESSField;
            }
            set {
                this.bRTADDRESSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT016E00")]
    public partial class TT016E00_EWAGNTL {
        
        private string aCCOUNTIDField;
        
        private TT016E00_EWAGNTLPERIODX pERIODXField;
        
        private string fREQUENCYField;
        
        private string aDJREFNOField;
        
        private string pREPARERNAMEField;
        
        private string pREPARERPHONEField;
        
        private string pREPARERPHONEEXTField;
        
        private string pREPARERIPADDRESSField;
        
        private string pREPAREREMAILField;
        
        private string pREPARERTYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PERIOD-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TT016E00_EWAGNTLPERIODX PERIODX {
            get {
                return this.pERIODXField;
            }
            set {
                this.pERIODXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FREQUENCY {
            get {
                return this.fREQUENCYField;
            }
            set {
                this.fREQUENCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADJ-REFNO", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADJREFNO {
            get {
                return this.aDJREFNOField;
            }
            set {
                this.aDJREFNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-NAME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERNAME {
            get {
                return this.pREPARERNAMEField;
            }
            set {
                this.pREPARERNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-PHONE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERPHONE {
            get {
                return this.pREPARERPHONEField;
            }
            set {
                this.pREPARERPHONEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-PHONE-EXT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERPHONEEXT {
            get {
                return this.pREPARERPHONEEXTField;
            }
            set {
                this.pREPARERPHONEEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-IP-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERIPADDRESS {
            get {
                return this.pREPARERIPADDRESSField;
            }
            set {
                this.pREPARERIPADDRESSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-EMAIL", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPAREREMAIL {
            get {
                return this.pREPAREREMAILField;
            }
            set {
                this.pREPAREREMAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERTYPE {
            get {
                return this.pREPARERTYPEField;
            }
            set {
                this.pREPARERTYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT016E00")]
    public partial class TT016E00_EWAGNTLPERIODX {
        
        private decimal pERIODField;
        
        private bool pERIODFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PERIOD {
            get {
                return this.pERIODField;
            }
            set {
                this.pERIODField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PERIODSpecified {
            get {
                return this.pERIODFieldSpecified;
            }
            set {
                this.pERIODFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT016E00")]
    public partial class TT016E00Response_SMA {
        
        private TT016E00Response_SMA_SYSTEMMESSAGEAREA _SYSTEMMESSAGEAREAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_SYSTEM-MESSAGE-AREA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TT016E00Response_SMA_SYSTEMMESSAGEAREA _SYSTEMMESSAGEAREA {
            get {
                return this._SYSTEMMESSAGEAREAField;
            }
            set {
                this._SYSTEMMESSAGEAREAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT016E00")]
    public partial class TT016E00Response_SMA_SYSTEMMESSAGEAREA {
        
        private string _PROGRAMField;
        
        private decimal eRRORField;
        
        private bool eRRORFieldSpecified;
        
        private decimal lINEField;
        
        private bool lINEFieldSpecified;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _PROGRAM {
            get {
                return this._PROGRAMField;
            }
            set {
                this._PROGRAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ERROR {
            get {
                return this.eRRORField;
            }
            set {
                this.eRRORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ERRORSpecified {
            get {
                return this.eRRORFieldSpecified;
            }
            set {
                this.eRRORFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal LINE {
            get {
                return this.lINEField;
            }
            set {
                this.lINEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LINESpecified {
            get {
                return this.lINEFieldSpecified;
            }
            set {
                this.lINEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT016E00")]
    public partial class TT016E00Response_EMI {
        
        private TT016E00Response_EMI_ENTITYMASTERINFO _ENTITYMASTERINFOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_ENTITY-MASTER-INFO", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TT016E00Response_EMI_ENTITYMASTERINFO _ENTITYMASTERINFO {
            get {
                return this._ENTITYMASTERINFOField;
            }
            set {
                this._ENTITYMASTERINFOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT016E00")]
    public partial class TT016E00Response_EMI_ENTITYMASTERINFO {
        
        private string fUNCTIONCODEField;
        
        private decimal eNTITYTYPEField;
        
        private bool eNTITYTYPEFieldSpecified;
        
        private string eNTITYIDField;
        
        private string aCCTIDField;
        
        private string eNTITYNAMEField;
        
        private string aDDRESSLINEField;
        
        private string aDDRESSLINE2Field;
        
        private string aDDRESSLINE3Field;
        
        private string cITYField;
        
        private string sTATEField;
        
        private string zIPCODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FUNCTION-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FUNCTIONCODE {
            get {
                return this.fUNCTIONCODEField;
            }
            set {
                this.fUNCTIONCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ENTITYTYPE {
            get {
                return this.eNTITYTYPEField;
            }
            set {
                this.eNTITYTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ENTITYTYPESpecified {
            get {
                return this.eNTITYTYPEFieldSpecified;
            }
            set {
                this.eNTITYTYPEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENTITYID {
            get {
                return this.eNTITYIDField;
            }
            set {
                this.eNTITYIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCTID {
            get {
                return this.aCCTIDField;
            }
            set {
                this.aCCTIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-NAME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENTITYNAME {
            get {
                return this.eNTITYNAMEField;
            }
            set {
                this.eNTITYNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADDRESS-LINE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADDRESSLINE {
            get {
                return this.aDDRESSLINEField;
            }
            set {
                this.aDDRESSLINEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADDRESS-LINE-2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADDRESSLINE2 {
            get {
                return this.aDDRESSLINE2Field;
            }
            set {
                this.aDDRESSLINE2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADDRESS-LINE-3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADDRESSLINE3 {
            get {
                return this.aDDRESSLINE3Field;
            }
            set {
                this.aDDRESSLINE3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CITY {
            get {
                return this.cITYField;
            }
            set {
                this.cITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STATE {
            get {
                return this.sTATEField;
            }
            set {
                this.sTATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ZIP-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZIPCODE {
            get {
                return this.zIPCODEField;
            }
            set {
                this.zIPCODEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT016E00")]
    public partial class TT016E00Response_ETA {
        
        private TT016E00Response_ETA_ENTITYTAXACCOUNTS[] _ENTITYTAXACCOUNTSsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("_ENTITY-TAX-ACCOUNTSs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_ENTITY-TAX-ACCOUNTS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public TT016E00Response_ETA_ENTITYTAXACCOUNTS[] _ENTITYTAXACCOUNTSs {
            get {
                return this._ENTITYTAXACCOUNTSsField;
            }
            set {
                this._ENTITYTAXACCOUNTSsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT016E00")]
    public partial class TT016E00Response_ETA_ENTITYTAXACCOUNTS {
        
        private string fUNCTIONCODEField;
        
        private decimal aCCOUNTField;
        
        private bool aCCOUNTFieldSpecified;
        
        private string aCCOUNTIDField;
        
        private decimal sTARTDATEField;
        
        private bool sTARTDATEFieldSpecified;
        
        private decimal eNDDATEField;
        
        private bool eNDDATEFieldSpecified;
        
        private string fREQUENCYField;
        
        private string bRTENTITYField;
        
        private string bRTADDRESSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FUNCTION-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FUNCTIONCODE {
            get {
                return this.fUNCTIONCODEField;
            }
            set {
                this.fUNCTIONCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ACCOUNT {
            get {
                return this.aCCOUNTField;
            }
            set {
                this.aCCOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ACCOUNTSpecified {
            get {
                return this.aCCOUNTFieldSpecified;
            }
            set {
                this.aCCOUNTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("START-DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal STARTDATE {
            get {
                return this.sTARTDATEField;
            }
            set {
                this.sTARTDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool STARTDATESpecified {
            get {
                return this.sTARTDATEFieldSpecified;
            }
            set {
                this.sTARTDATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("END-DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ENDDATE {
            get {
                return this.eNDDATEField;
            }
            set {
                this.eNDDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ENDDATESpecified {
            get {
                return this.eNDDATEFieldSpecified;
            }
            set {
                this.eNDDATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FREQUENCY {
            get {
                return this.fREQUENCYField;
            }
            set {
                this.fREQUENCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BRT-ENTITY", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRTENTITY {
            get {
                return this.bRTENTITYField;
            }
            set {
                this.bRTENTITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BRT-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRTADDRESS {
            get {
                return this.bRTADDRESSField;
            }
            set {
                this.bRTADDRESSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT016E00")]
    public partial class TT016E00Response_EWAGNTL {
        
        private string aCCOUNTIDField;
        
        private TT016E00Response_EWAGNTLPERIODX pERIODXField;
        
        private string fREQUENCYField;
        
        private string aDJREFNOField;
        
        private string pREPARERNAMEField;
        
        private string pREPARERPHONEField;
        
        private string pREPARERPHONEEXTField;
        
        private string pREPARERIPADDRESSField;
        
        private string pREPAREREMAILField;
        
        private string pREPARERTYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PERIOD-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TT016E00Response_EWAGNTLPERIODX PERIODX {
            get {
                return this.pERIODXField;
            }
            set {
                this.pERIODXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FREQUENCY {
            get {
                return this.fREQUENCYField;
            }
            set {
                this.fREQUENCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADJ-REFNO", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADJREFNO {
            get {
                return this.aDJREFNOField;
            }
            set {
                this.aDJREFNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-NAME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERNAME {
            get {
                return this.pREPARERNAMEField;
            }
            set {
                this.pREPARERNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-PHONE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERPHONE {
            get {
                return this.pREPARERPHONEField;
            }
            set {
                this.pREPARERPHONEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-PHONE-EXT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERPHONEEXT {
            get {
                return this.pREPARERPHONEEXTField;
            }
            set {
                this.pREPARERPHONEEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-IP-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERIPADDRESS {
            get {
                return this.pREPARERIPADDRESSField;
            }
            set {
                this.pREPARERIPADDRESSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-EMAIL", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPAREREMAIL {
            get {
                return this.pREPAREREMAILField;
            }
            set {
                this.pREPAREREMAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERTYPE {
            get {
                return this.pREPARERTYPEField;
            }
            set {
                this.pREPARERTYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT016E00")]
    public partial class TT016E00Response_EWAGNTLPERIODX {
        
        private decimal pERIODField;
        
        private bool pERIODFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PERIOD {
            get {
                return this.pERIODField;
            }
            set {
                this.pERIODField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PERIODSpecified {
            get {
                return this.pERIODFieldSpecified;
            }
            set {
                this.pERIODFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CallTT016E00CompletedEventHandler(object sender, CallTT016E00CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallTT016E00CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallTT016E00CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TT016E00Response_SMA Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TT016E00Response_SMA)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TT016E00Response_EMI _EMI1 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TT016E00Response_EMI)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public TT016E00Response_ETA _ETA1 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TT016E00Response_ETA)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public TT016E00Response_EWAGNTL _EWAGNTL1 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TT016E00Response_EWAGNTL)(this.results[3]));
            }
        }
    }
}

#pragma warning restore 1591