//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18063.
// 
#pragma warning disable 1591

namespace CopRevenueGov2.RTTIE040_SrvRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TIPSACCTSOAP11Binding", Namespace="http://namespace.softwareag.com/entirex/xml/mapping")]
    public partial class TT040E00 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CallTT040E00OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TT040E00() {
            this.Url = "http://192.168.204.70:10010/wsstack/services/TT040E00.TIPSACCTSOAP11Port/";
                
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallTT040E00CompletedEventHandler CallTT040E00Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TT040E00", RequestElementName="TT040E00", RequestNamespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT040E00", ResponseElementName="TT040E00Response", ResponseNamespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT040E00", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("_SMA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TT040E00Response_SMA CallTT040E00([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] TT040E00_SMA _SMA, [System.Xml.Serialization.XmlElementAttribute("_E-NPT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] TT040E00_ENPT _ENPT, [System.Xml.Serialization.XmlElementAttribute("_E-AMTS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] TT040E00_EAMTS _EAMTS, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] TT040E00_SERR _SERR, [System.Xml.Serialization.XmlElementAttribute("_E-NPT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out TT040E00Response_ENPT _ENPT1, [System.Xml.Serialization.XmlElementAttribute("_E-AMTS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out TT040E00Response_EAMTS _EAMTS1, [System.Xml.Serialization.XmlElementAttribute("_SERR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out TT040E00Response_SERR _SERR1) {
            object[] results = this.Invoke("CallTT040E00", new object[] {
                        _SMA,
                        _ENPT,
                        _EAMTS,
                        _SERR});
            _ENPT1 = ((TT040E00Response_ENPT)(results[1]));
            _EAMTS1 = ((TT040E00Response_EAMTS)(results[2]));
            _SERR1 = ((TT040E00Response_SERR)(results[3]));
            return ((TT040E00Response_SMA)(results[0]));
        }
        
        /// <remarks/>
        public void CallTT040E00Async(TT040E00_SMA _SMA, TT040E00_ENPT _ENPT, TT040E00_EAMTS _EAMTS, TT040E00_SERR _SERR) {
            this.CallTT040E00Async(_SMA, _ENPT, _EAMTS, _SERR, null);
        }
        
        /// <remarks/>
        public void CallTT040E00Async(TT040E00_SMA _SMA, TT040E00_ENPT _ENPT, TT040E00_EAMTS _EAMTS, TT040E00_SERR _SERR, object userState) {
            if ((this.CallTT040E00OperationCompleted == null)) {
                this.CallTT040E00OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallTT040E00OperationCompleted);
            }
            this.InvokeAsync("CallTT040E00", new object[] {
                        _SMA,
                        _ENPT,
                        _EAMTS,
                        _SERR}, this.CallTT040E00OperationCompleted, userState);
        }
        
        private void OnCallTT040E00OperationCompleted(object arg) {
            if ((this.CallTT040E00Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallTT040E00Completed(this, new CallTT040E00CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT040E00")]
    public partial class TT040E00_SMA {
        
        private string _PROGRAMField;
        
        private decimal sYSTEMERRORField;
        
        private bool sYSTEMERRORFieldSpecified;
        
        private decimal eRRORLINEField;
        
        private bool eRRORLINEFieldSpecified;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _PROGRAM {
            get {
                return this._PROGRAMField;
            }
            set {
                this._PROGRAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SYSTEM-ERROR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SYSTEMERROR {
            get {
                return this.sYSTEMERRORField;
            }
            set {
                this.sYSTEMERRORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SYSTEMERRORSpecified {
            get {
                return this.sYSTEMERRORFieldSpecified;
            }
            set {
                this.sYSTEMERRORFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ERROR-LINE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ERRORLINE {
            get {
                return this.eRRORLINEField;
            }
            set {
                this.eRRORLINEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ERRORLINESpecified {
            get {
                return this.eRRORLINEFieldSpecified;
            }
            set {
                this.eRRORLINEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT040E00")]
    public partial class TT040E00_ENPT {
        
        private string aCCOUNTIDField;
        
        private string pERIODXField;
        
        private string vERSIONXField;
        
        private string rETURNSTATUSField;
        
        private string lASTUPDATEDATEXField;
        
        private string rECORDINGDATEXField;
        
        private string eXTENSIONDATEXField;
        
        private string sEQUENCENUMBERField;
        
        private string aDJUSTMENTREFERENCENUMField;
        
        private string uSERIDField;
        
        private string rATERESField;
        
        private string bASERATERESField;
        
        private string rATENONRESField;
        
        private string bASERATENONRESField;
        
        private string cORPPARTNERINDField;
        
        private string pREPARERNAMEField;
        
        private decimal pREPARERPHONEField;
        
        private bool pREPARERPHONEFieldSpecified;
        
        private string pREPARERPHONEEXTField;
        
        private string pREPARERIPADDRESSField;
        
        private string pREPAREREMAILADDRESSField;
        
        private string pREPARERTYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PERIOD-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERIODX {
            get {
                return this.pERIODXField;
            }
            set {
                this.pERIODXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VERSION-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VERSIONX {
            get {
                return this.vERSIONXField;
            }
            set {
                this.vERSIONXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RETURN-STATUS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RETURNSTATUS {
            get {
                return this.rETURNSTATUSField;
            }
            set {
                this.rETURNSTATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LAST-UPDATE-DATE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LASTUPDATEDATEX {
            get {
                return this.lASTUPDATEDATEXField;
            }
            set {
                this.lASTUPDATEDATEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RECORDING-DATE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RECORDINGDATEX {
            get {
                return this.rECORDINGDATEXField;
            }
            set {
                this.rECORDINGDATEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EXTENSION-DATE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EXTENSIONDATEX {
            get {
                return this.eXTENSIONDATEXField;
            }
            set {
                this.eXTENSIONDATEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SEQUENCE-NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SEQUENCENUMBER {
            get {
                return this.sEQUENCENUMBERField;
            }
            set {
                this.sEQUENCENUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADJUSTMENT-REFERENCE-NUM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADJUSTMENTREFERENCENUM {
            get {
                return this.aDJUSTMENTREFERENCENUMField;
            }
            set {
                this.aDJUSTMENTREFERENCENUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("USER-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERID {
            get {
                return this.uSERIDField;
            }
            set {
                this.uSERIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RATE-RES", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RATERES {
            get {
                return this.rATERESField;
            }
            set {
                this.rATERESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BASERATE-RES", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BASERATERES {
            get {
                return this.bASERATERESField;
            }
            set {
                this.bASERATERESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RATE-NON-RES", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RATENONRES {
            get {
                return this.rATENONRESField;
            }
            set {
                this.rATENONRESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BASERATE-NON-RES", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BASERATENONRES {
            get {
                return this.bASERATENONRESField;
            }
            set {
                this.bASERATENONRESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CORP-PARTNER-IND", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CORPPARTNERIND {
            get {
                return this.cORPPARTNERINDField;
            }
            set {
                this.cORPPARTNERINDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-NAME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERNAME {
            get {
                return this.pREPARERNAMEField;
            }
            set {
                this.pREPARERNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-PHONE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PREPARERPHONE {
            get {
                return this.pREPARERPHONEField;
            }
            set {
                this.pREPARERPHONEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PREPARERPHONESpecified {
            get {
                return this.pREPARERPHONEFieldSpecified;
            }
            set {
                this.pREPARERPHONEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-PHONE-EXT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERPHONEEXT {
            get {
                return this.pREPARERPHONEEXTField;
            }
            set {
                this.pREPARERPHONEEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-IP-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERIPADDRESS {
            get {
                return this.pREPARERIPADDRESSField;
            }
            set {
                this.pREPARERIPADDRESSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-EMAIL-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPAREREMAILADDRESS {
            get {
                return this.pREPAREREMAILADDRESSField;
            }
            set {
                this.pREPAREREMAILADDRESSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERTYPE {
            get {
                return this.pREPARERTYPEField;
            }
            set {
                this.pREPARERTYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT040E00")]
    public partial class TT040E00_EAMTS {
        
        private string cORPPARTNERPERCENTXField;
        
        private string rESTAXABLEINCOMEXField;
        
        private string rESTAXDUEXField;
        
        private string rESBASERATETAXABLEXField;
        
        private string rESBASERATETAXXField;
        
        private string tOTALRESTAXXField;
        
        private string nONRESTAXINCOMEXField;
        
        private string nONRESTAXDUEXField;
        
        private string nONRESBASERATETAXABLEXField;
        
        private string nONRESBASERATETAXXField;
        
        private string tOTALNONRESTAXXField;
        
        private string tOTALTAXDUE1XField;
        
        private string bPTCREDITXField;
        
        private string oTHERXField;
        
        private string tOTALCREDITSXField;
        
        private string tOTALTAXDUEXField;
        
        private string iNTERESTPENALTYXField;
        
        private string tOTALAMTDUEXField;
        
        private string tAXOVERPAIDXField;
        
        private string nETPROFITESTXField;
        
        private string oVERPAYMENTAVAILXField;
        
        private string rEFUNDAMTXField;
        
        private string bPTOVERPAYMENTXField;
        
        private string nPTOVERPAYMENTXField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CORP-PARTNER-PERCENT-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CORPPARTNERPERCENTX {
            get {
                return this.cORPPARTNERPERCENTXField;
            }
            set {
                this.cORPPARTNERPERCENTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RES-TAXABLE-INCOME-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESTAXABLEINCOMEX {
            get {
                return this.rESTAXABLEINCOMEXField;
            }
            set {
                this.rESTAXABLEINCOMEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RES-TAX-DUE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESTAXDUEX {
            get {
                return this.rESTAXDUEXField;
            }
            set {
                this.rESTAXDUEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RES-BASERATE-TAXABLE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESBASERATETAXABLEX {
            get {
                return this.rESBASERATETAXABLEXField;
            }
            set {
                this.rESBASERATETAXABLEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RES-BASERATE-TAX-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESBASERATETAXX {
            get {
                return this.rESBASERATETAXXField;
            }
            set {
                this.rESBASERATETAXXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOTAL-RES-TAX-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TOTALRESTAXX {
            get {
                return this.tOTALRESTAXXField;
            }
            set {
                this.tOTALRESTAXXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RES-TAX-INCOME-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NONRESTAXINCOMEX {
            get {
                return this.nONRESTAXINCOMEXField;
            }
            set {
                this.nONRESTAXINCOMEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RES-TAX-DUE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NONRESTAXDUEX {
            get {
                return this.nONRESTAXDUEXField;
            }
            set {
                this.nONRESTAXDUEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RES-BASERATE-TAXABLE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NONRESBASERATETAXABLEX {
            get {
                return this.nONRESBASERATETAXABLEXField;
            }
            set {
                this.nONRESBASERATETAXABLEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RES-BASERATE-TAX-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NONRESBASERATETAXX {
            get {
                return this.nONRESBASERATETAXXField;
            }
            set {
                this.nONRESBASERATETAXXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOTAL-NON-RES-TAX-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TOTALNONRESTAXX {
            get {
                return this.tOTALNONRESTAXXField;
            }
            set {
                this.tOTALNONRESTAXXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOTAL-TAX-DUE-1-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TOTALTAXDUE1X {
            get {
                return this.tOTALTAXDUE1XField;
            }
            set {
                this.tOTALTAXDUE1XField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BPT-CREDIT-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BPTCREDITX {
            get {
                return this.bPTCREDITXField;
            }
            set {
                this.bPTCREDITXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OTHER-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OTHERX {
            get {
                return this.oTHERXField;
            }
            set {
                this.oTHERXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOTAL-CREDITS-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TOTALCREDITSX {
            get {
                return this.tOTALCREDITSXField;
            }
            set {
                this.tOTALCREDITSXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOTAL-TAX-DUE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TOTALTAXDUEX {
            get {
                return this.tOTALTAXDUEXField;
            }
            set {
                this.tOTALTAXDUEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("INTEREST-PENALTY-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTERESTPENALTYX {
            get {
                return this.iNTERESTPENALTYXField;
            }
            set {
                this.iNTERESTPENALTYXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOTAL-AMT-DUE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TOTALAMTDUEX {
            get {
                return this.tOTALAMTDUEXField;
            }
            set {
                this.tOTALAMTDUEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAX-OVERPAID-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TAXOVERPAIDX {
            get {
                return this.tAXOVERPAIDXField;
            }
            set {
                this.tAXOVERPAIDXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NET-PROFIT-EST-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NETPROFITESTX {
            get {
                return this.nETPROFITESTXField;
            }
            set {
                this.nETPROFITESTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OVERPAYMENT-AVAIL-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OVERPAYMENTAVAILX {
            get {
                return this.oVERPAYMENTAVAILXField;
            }
            set {
                this.oVERPAYMENTAVAILXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("REFUND-AMT-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REFUNDAMTX {
            get {
                return this.rEFUNDAMTXField;
            }
            set {
                this.rEFUNDAMTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BPT-OVERPAYMENT-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BPTOVERPAYMENTX {
            get {
                return this.bPTOVERPAYMENTXField;
            }
            set {
                this.bPTOVERPAYMENTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NPT-OVERPAYMENT-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NPTOVERPAYMENTX {
            get {
                return this.nPTOVERPAYMENTXField;
            }
            set {
                this.nPTOVERPAYMENTXField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT040E00")]
    public partial class TT040E00_SERR {
        
        private string _SERRPROGRAMField;
        
        private decimal _SERRNUMBERField;
        
        private bool _SERRNUMBERFieldSpecified;
        
        private decimal _SERRLINEField;
        
        private bool _SERRLINEFieldSpecified;
        
        private string _SERRDATEField;
        
        private string _SERRTIMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_SERR-PROGRAM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _SERRPROGRAM {
            get {
                return this._SERRPROGRAMField;
            }
            set {
                this._SERRPROGRAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_SERR-NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal _SERRNUMBER {
            get {
                return this._SERRNUMBERField;
            }
            set {
                this._SERRNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool _SERRNUMBERSpecified {
            get {
                return this._SERRNUMBERFieldSpecified;
            }
            set {
                this._SERRNUMBERFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_SERR-LINE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal _SERRLINE {
            get {
                return this._SERRLINEField;
            }
            set {
                this._SERRLINEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool _SERRLINESpecified {
            get {
                return this._SERRLINEFieldSpecified;
            }
            set {
                this._SERRLINEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_SERR-DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _SERRDATE {
            get {
                return this._SERRDATEField;
            }
            set {
                this._SERRDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_SERR-TIME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _SERRTIME {
            get {
                return this._SERRTIMEField;
            }
            set {
                this._SERRTIMEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT040E00")]
    public partial class TT040E00Response_SMA {
        
        private string _PROGRAMField;
        
        private decimal sYSTEMERRORField;
        
        private bool sYSTEMERRORFieldSpecified;
        
        private decimal eRRORLINEField;
        
        private bool eRRORLINEFieldSpecified;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _PROGRAM {
            get {
                return this._PROGRAMField;
            }
            set {
                this._PROGRAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SYSTEM-ERROR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SYSTEMERROR {
            get {
                return this.sYSTEMERRORField;
            }
            set {
                this.sYSTEMERRORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SYSTEMERRORSpecified {
            get {
                return this.sYSTEMERRORFieldSpecified;
            }
            set {
                this.sYSTEMERRORFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ERROR-LINE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ERRORLINE {
            get {
                return this.eRRORLINEField;
            }
            set {
                this.eRRORLINEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ERRORLINESpecified {
            get {
                return this.eRRORLINEFieldSpecified;
            }
            set {
                this.eRRORLINEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT040E00")]
    public partial class TT040E00Response_ENPT {
        
        private string aCCOUNTIDField;
        
        private string pERIODXField;
        
        private string vERSIONXField;
        
        private string rETURNSTATUSField;
        
        private string lASTUPDATEDATEXField;
        
        private string rECORDINGDATEXField;
        
        private string eXTENSIONDATEXField;
        
        private string sEQUENCENUMBERField;
        
        private string aDJUSTMENTREFERENCENUMField;
        
        private string uSERIDField;
        
        private string rATERESField;
        
        private string bASERATERESField;
        
        private string rATENONRESField;
        
        private string bASERATENONRESField;
        
        private string cORPPARTNERINDField;
        
        private string pREPARERNAMEField;
        
        private decimal pREPARERPHONEField;
        
        private bool pREPARERPHONEFieldSpecified;
        
        private string pREPARERPHONEEXTField;
        
        private string pREPARERIPADDRESSField;
        
        private string pREPAREREMAILADDRESSField;
        
        private string pREPARERTYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PERIOD-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERIODX {
            get {
                return this.pERIODXField;
            }
            set {
                this.pERIODXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VERSION-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VERSIONX {
            get {
                return this.vERSIONXField;
            }
            set {
                this.vERSIONXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RETURN-STATUS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RETURNSTATUS {
            get {
                return this.rETURNSTATUSField;
            }
            set {
                this.rETURNSTATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LAST-UPDATE-DATE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LASTUPDATEDATEX {
            get {
                return this.lASTUPDATEDATEXField;
            }
            set {
                this.lASTUPDATEDATEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RECORDING-DATE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RECORDINGDATEX {
            get {
                return this.rECORDINGDATEXField;
            }
            set {
                this.rECORDINGDATEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EXTENSION-DATE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EXTENSIONDATEX {
            get {
                return this.eXTENSIONDATEXField;
            }
            set {
                this.eXTENSIONDATEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SEQUENCE-NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SEQUENCENUMBER {
            get {
                return this.sEQUENCENUMBERField;
            }
            set {
                this.sEQUENCENUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADJUSTMENT-REFERENCE-NUM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADJUSTMENTREFERENCENUM {
            get {
                return this.aDJUSTMENTREFERENCENUMField;
            }
            set {
                this.aDJUSTMENTREFERENCENUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("USER-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERID {
            get {
                return this.uSERIDField;
            }
            set {
                this.uSERIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RATE-RES", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RATERES {
            get {
                return this.rATERESField;
            }
            set {
                this.rATERESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BASERATE-RES", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BASERATERES {
            get {
                return this.bASERATERESField;
            }
            set {
                this.bASERATERESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RATE-NON-RES", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RATENONRES {
            get {
                return this.rATENONRESField;
            }
            set {
                this.rATENONRESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BASERATE-NON-RES", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BASERATENONRES {
            get {
                return this.bASERATENONRESField;
            }
            set {
                this.bASERATENONRESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CORP-PARTNER-IND", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CORPPARTNERIND {
            get {
                return this.cORPPARTNERINDField;
            }
            set {
                this.cORPPARTNERINDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-NAME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERNAME {
            get {
                return this.pREPARERNAMEField;
            }
            set {
                this.pREPARERNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-PHONE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PREPARERPHONE {
            get {
                return this.pREPARERPHONEField;
            }
            set {
                this.pREPARERPHONEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PREPARERPHONESpecified {
            get {
                return this.pREPARERPHONEFieldSpecified;
            }
            set {
                this.pREPARERPHONEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-PHONE-EXT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERPHONEEXT {
            get {
                return this.pREPARERPHONEEXTField;
            }
            set {
                this.pREPARERPHONEEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-IP-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERIPADDRESS {
            get {
                return this.pREPARERIPADDRESSField;
            }
            set {
                this.pREPARERIPADDRESSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-EMAIL-ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPAREREMAILADDRESS {
            get {
                return this.pREPAREREMAILADDRESSField;
            }
            set {
                this.pREPAREREMAILADDRESSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PREPARER-TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PREPARERTYPE {
            get {
                return this.pREPARERTYPEField;
            }
            set {
                this.pREPARERTYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT040E00")]
    public partial class TT040E00Response_EAMTS {
        
        private string cORPPARTNERPERCENTXField;
        
        private string rESTAXABLEINCOMEXField;
        
        private string rESTAXDUEXField;
        
        private string rESBASERATETAXABLEXField;
        
        private string rESBASERATETAXXField;
        
        private string tOTALRESTAXXField;
        
        private string nONRESTAXINCOMEXField;
        
        private string nONRESTAXDUEXField;
        
        private string nONRESBASERATETAXABLEXField;
        
        private string nONRESBASERATETAXXField;
        
        private string tOTALNONRESTAXXField;
        
        private string tOTALTAXDUE1XField;
        
        private string bPTCREDITXField;
        
        private string oTHERXField;
        
        private string tOTALCREDITSXField;
        
        private string tOTALTAXDUEXField;
        
        private string iNTERESTPENALTYXField;
        
        private string tOTALAMTDUEXField;
        
        private string tAXOVERPAIDXField;
        
        private string nETPROFITESTXField;
        
        private string oVERPAYMENTAVAILXField;
        
        private string rEFUNDAMTXField;
        
        private string bPTOVERPAYMENTXField;
        
        private string nPTOVERPAYMENTXField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CORP-PARTNER-PERCENT-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CORPPARTNERPERCENTX {
            get {
                return this.cORPPARTNERPERCENTXField;
            }
            set {
                this.cORPPARTNERPERCENTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RES-TAXABLE-INCOME-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESTAXABLEINCOMEX {
            get {
                return this.rESTAXABLEINCOMEXField;
            }
            set {
                this.rESTAXABLEINCOMEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RES-TAX-DUE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESTAXDUEX {
            get {
                return this.rESTAXDUEXField;
            }
            set {
                this.rESTAXDUEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RES-BASERATE-TAXABLE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESBASERATETAXABLEX {
            get {
                return this.rESBASERATETAXABLEXField;
            }
            set {
                this.rESBASERATETAXABLEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RES-BASERATE-TAX-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESBASERATETAXX {
            get {
                return this.rESBASERATETAXXField;
            }
            set {
                this.rESBASERATETAXXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOTAL-RES-TAX-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TOTALRESTAXX {
            get {
                return this.tOTALRESTAXXField;
            }
            set {
                this.tOTALRESTAXXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RES-TAX-INCOME-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NONRESTAXINCOMEX {
            get {
                return this.nONRESTAXINCOMEXField;
            }
            set {
                this.nONRESTAXINCOMEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RES-TAX-DUE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NONRESTAXDUEX {
            get {
                return this.nONRESTAXDUEXField;
            }
            set {
                this.nONRESTAXDUEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RES-BASERATE-TAXABLE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NONRESBASERATETAXABLEX {
            get {
                return this.nONRESBASERATETAXABLEXField;
            }
            set {
                this.nONRESBASERATETAXABLEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NON-RES-BASERATE-TAX-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NONRESBASERATETAXX {
            get {
                return this.nONRESBASERATETAXXField;
            }
            set {
                this.nONRESBASERATETAXXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOTAL-NON-RES-TAX-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TOTALNONRESTAXX {
            get {
                return this.tOTALNONRESTAXXField;
            }
            set {
                this.tOTALNONRESTAXXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOTAL-TAX-DUE-1-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TOTALTAXDUE1X {
            get {
                return this.tOTALTAXDUE1XField;
            }
            set {
                this.tOTALTAXDUE1XField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BPT-CREDIT-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BPTCREDITX {
            get {
                return this.bPTCREDITXField;
            }
            set {
                this.bPTCREDITXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OTHER-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OTHERX {
            get {
                return this.oTHERXField;
            }
            set {
                this.oTHERXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOTAL-CREDITS-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TOTALCREDITSX {
            get {
                return this.tOTALCREDITSXField;
            }
            set {
                this.tOTALCREDITSXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOTAL-TAX-DUE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TOTALTAXDUEX {
            get {
                return this.tOTALTAXDUEXField;
            }
            set {
                this.tOTALTAXDUEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("INTEREST-PENALTY-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTERESTPENALTYX {
            get {
                return this.iNTERESTPENALTYXField;
            }
            set {
                this.iNTERESTPENALTYXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOTAL-AMT-DUE-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TOTALAMTDUEX {
            get {
                return this.tOTALAMTDUEXField;
            }
            set {
                this.tOTALAMTDUEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAX-OVERPAID-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TAXOVERPAIDX {
            get {
                return this.tAXOVERPAIDXField;
            }
            set {
                this.tAXOVERPAIDXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NET-PROFIT-EST-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NETPROFITESTX {
            get {
                return this.nETPROFITESTXField;
            }
            set {
                this.nETPROFITESTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OVERPAYMENT-AVAIL-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OVERPAYMENTAVAILX {
            get {
                return this.oVERPAYMENTAVAILXField;
            }
            set {
                this.oVERPAYMENTAVAILXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("REFUND-AMT-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REFUNDAMTX {
            get {
                return this.rEFUNDAMTXField;
            }
            set {
                this.rEFUNDAMTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BPT-OVERPAYMENT-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BPTOVERPAYMENTX {
            get {
                return this.bPTOVERPAYMENTXField;
            }
            set {
                this.bPTOVERPAYMENTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NPT-OVERPAYMENT-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NPTOVERPAYMENTX {
            get {
                return this.nPTOVERPAYMENTXField;
            }
            set {
                this.nPTOVERPAYMENTXField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT040E00")]
    public partial class TT040E00Response_SERR {
        
        private string _SERRPROGRAMField;
        
        private decimal _SERRNUMBERField;
        
        private bool _SERRNUMBERFieldSpecified;
        
        private decimal _SERRLINEField;
        
        private bool _SERRLINEFieldSpecified;
        
        private string _SERRDATEField;
        
        private string _SERRTIMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_SERR-PROGRAM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _SERRPROGRAM {
            get {
                return this._SERRPROGRAMField;
            }
            set {
                this._SERRPROGRAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_SERR-NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal _SERRNUMBER {
            get {
                return this._SERRNUMBERField;
            }
            set {
                this._SERRNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool _SERRNUMBERSpecified {
            get {
                return this._SERRNUMBERFieldSpecified;
            }
            set {
                this._SERRNUMBERFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_SERR-LINE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal _SERRLINE {
            get {
                return this._SERRLINEField;
            }
            set {
                this._SERRLINEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool _SERRLINESpecified {
            get {
                return this._SERRLINEFieldSpecified;
            }
            set {
                this._SERRLINEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_SERR-DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _SERRDATE {
            get {
                return this._SERRDATEField;
            }
            set {
                this._SERRDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_SERR-TIME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _SERRTIME {
            get {
                return this._SERRTIMEField;
            }
            set {
                this._SERRTIMEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CallTT040E00CompletedEventHandler(object sender, CallTT040E00CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallTT040E00CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallTT040E00CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TT040E00Response_SMA Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TT040E00Response_SMA)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TT040E00Response_ENPT _ENPT1 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TT040E00Response_ENPT)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public TT040E00Response_EAMTS _EAMTS1 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TT040E00Response_EAMTS)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public TT040E00Response_SERR _SERR1 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TT040E00Response_SERR)(this.results[3]));
            }
        }
    }
}

#pragma warning restore 1591