//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18063.
// 
#pragma warning disable 1591

namespace CopRevenueGov2.UOList_RTTIE034_SrvRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TIPSACCTSOAP11Binding", Namespace="http://namespace.softwareag.com/entirex/xml/mapping")]
    public partial class TT034E00 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CallTT034E00OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TT034E00() {
            this.Url = "http://192.168.204.70:10010/wsstack/services/TT034E00.TIPSACCTSOAP11Port/";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallTT034E00CompletedEventHandler CallTT034E00Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TT034E00", RequestElementName="TT034E00", RequestNamespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT034E00", ResponseElementName="TT034E00Response", ResponseNamespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT034E00", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("_SMA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TT034E00Response_SMA CallTT034E00([System.Xml.Serialization.XmlElementAttribute("_E-REQ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] TT034E00_EREQ _EREQ, [System.Xml.Serialization.XmlElementAttribute("_E-LIST", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] TT034E00_ELIST _ELIST, [System.Xml.Serialization.XmlElementAttribute("_E-REQ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out TT034E00Response_EREQ _EREQ1, [System.Xml.Serialization.XmlElementAttribute("_E-LIST", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out TT034E00Response_ELIST _ELIST1) {
            object[] results = this.Invoke("CallTT034E00", new object[] {
                        _EREQ,
                        _ELIST});
            _EREQ1 = ((TT034E00Response_EREQ)(results[1]));
            _ELIST1 = ((TT034E00Response_ELIST)(results[2]));
            return ((TT034E00Response_SMA)(results[0]));
        }
        
        /// <remarks/>
        public void CallTT034E00Async(TT034E00_EREQ _EREQ, TT034E00_ELIST _ELIST) {
            this.CallTT034E00Async(_EREQ, _ELIST, null);
        }
        
        /// <remarks/>
        public void CallTT034E00Async(TT034E00_EREQ _EREQ, TT034E00_ELIST _ELIST, object userState) {
            if ((this.CallTT034E00OperationCompleted == null)) {
                this.CallTT034E00OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallTT034E00OperationCompleted);
            }
            this.InvokeAsync("CallTT034E00", new object[] {
                        _EREQ,
                        _ELIST}, this.CallTT034E00OperationCompleted, userState);
        }
        
        private void OnCallTT034E00OperationCompleted(object arg) {
            if ((this.CallTT034E00Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallTT034E00Completed(this, new CallTT034E00CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT034E00")]
    public partial class TT034E00_EREQ {
        
        private string eNTITYIDField;
        
        private string aCCOUNTIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENTITYID {
            get {
                return this.eNTITYIDField;
            }
            set {
                this.eNTITYIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT034E00")]
    public partial class TT034E00_ELIST {
        
        private TT034E00_ELIST_UOLACCOUNTS[] _UOLACCOUNTSsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("_UOL-ACCOUNTSs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_UOL-ACCOUNTS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public TT034E00_ELIST_UOLACCOUNTS[] _UOLACCOUNTSs {
            get {
                return this._UOLACCOUNTSsField;
            }
            set {
                this._UOLACCOUNTSsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT034E00")]
    public partial class TT034E00_ELIST_UOLACCOUNTS {
        
        private TT034E00_ELIST_UOLACCOUNTSACCOUNTIDX aCCOUNTIDXField;
        
        private string bRTNUMBERField;
        
        private string lOCATIONField;
        
        private string sTARTDATEField;
        
        private string eNDDATEField;
        
        private TT034E00_ELIST_UOLACCOUNTSFREQTABLE fREQTABLEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TT034E00_ELIST_UOLACCOUNTSACCOUNTIDX ACCOUNTIDX {
            get {
                return this.aCCOUNTIDXField;
            }
            set {
                this.aCCOUNTIDXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BRT-NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRTNUMBER {
            get {
                return this.bRTNUMBERField;
            }
            set {
                this.bRTNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOCATION {
            get {
                return this.lOCATIONField;
            }
            set {
                this.lOCATIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("START-DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STARTDATE {
            get {
                return this.sTARTDATEField;
            }
            set {
                this.sTARTDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("END-DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENDDATE {
            get {
                return this.eNDDATEField;
            }
            set {
                this.eNDDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FREQ-TABLE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TT034E00_ELIST_UOLACCOUNTSFREQTABLE FREQTABLE {
            get {
                return this.fREQTABLEField;
            }
            set {
                this.fREQTABLEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT034E00")]
    public partial class TT034E00_ELIST_UOLACCOUNTSACCOUNTIDX {
        
        private string aCCOUNTIDField;
        
        private string aNNUALELIGIBLEField;
        
        private string aSSESSMENTINDField;
        
        private string fILLERXField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ANNUAL-ELIGIBLE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ANNUALELIGIBLE {
            get {
                return this.aNNUALELIGIBLEField;
            }
            set {
                this.aNNUALELIGIBLEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ASSESSMENT-IND", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ASSESSMENTIND {
            get {
                return this.aSSESSMENTINDField;
            }
            set {
                this.aSSESSMENTINDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FILLER-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FILLERX {
            get {
                return this.fILLERXField;
            }
            set {
                this.fILLERXField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT034E00")]
    public partial class TT034E00_ELIST_UOLACCOUNTSFREQTABLE {
        
        private TT034E00_ELIST_UOLACCOUNTSFREQTABLEFREQ[] fREQsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("FREQ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public TT034E00_ELIST_UOLACCOUNTSFREQTABLEFREQ[] FREQs {
            get {
                return this.fREQsField;
            }
            set {
                this.fREQsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT034E00")]
    public partial class TT034E00_ELIST_UOLACCOUNTSFREQTABLEFREQ {
        
        private string fREQCODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FREQ-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FREQCODE {
            get {
                return this.fREQCODEField;
            }
            set {
                this.fREQCODEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT034E00")]
    public partial class TT034E00Response_SMA {
        
        private string _PROGRAMField;
        
        private decimal sYSTEMERRORField;
        
        private bool sYSTEMERRORFieldSpecified;
        
        private decimal eRRORLINEField;
        
        private bool eRRORLINEFieldSpecified;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _PROGRAM {
            get {
                return this._PROGRAMField;
            }
            set {
                this._PROGRAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SYSTEM-ERROR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SYSTEMERROR {
            get {
                return this.sYSTEMERRORField;
            }
            set {
                this.sYSTEMERRORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SYSTEMERRORSpecified {
            get {
                return this.sYSTEMERRORFieldSpecified;
            }
            set {
                this.sYSTEMERRORFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ERROR-LINE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ERRORLINE {
            get {
                return this.eRRORLINEField;
            }
            set {
                this.eRRORLINEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ERRORLINESpecified {
            get {
                return this.eRRORLINEFieldSpecified;
            }
            set {
                this.eRRORLINEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT034E00")]
    public partial class TT034E00Response_EREQ {
        
        private string eNTITYIDField;
        
        private string aCCOUNTIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ENTITY-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENTITYID {
            get {
                return this.eNTITYIDField;
            }
            set {
                this.eNTITYIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT034E00")]
    public partial class TT034E00Response_ELIST {
        
        private TT034E00Response_ELIST_UOLACCOUNTS[] _UOLACCOUNTSsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("_UOL-ACCOUNTSs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_UOL-ACCOUNTS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public TT034E00Response_ELIST_UOLACCOUNTS[] _UOLACCOUNTSs {
            get {
                return this._UOLACCOUNTSsField;
            }
            set {
                this._UOLACCOUNTSsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT034E00")]
    public partial class TT034E00Response_ELIST_UOLACCOUNTS {
        
        private TT034E00Response_ELIST_UOLACCOUNTSACCOUNTIDX aCCOUNTIDXField;
        
        private string bRTNUMBERField;
        
        private string lOCATIONField;
        
        private string sTARTDATEField;
        
        private string eNDDATEField;
        
        private TT034E00Response_ELIST_UOLACCOUNTSFREQTABLE fREQTABLEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TT034E00Response_ELIST_UOLACCOUNTSACCOUNTIDX ACCOUNTIDX {
            get {
                return this.aCCOUNTIDXField;
            }
            set {
                this.aCCOUNTIDXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BRT-NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRTNUMBER {
            get {
                return this.bRTNUMBERField;
            }
            set {
                this.bRTNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOCATION {
            get {
                return this.lOCATIONField;
            }
            set {
                this.lOCATIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("START-DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STARTDATE {
            get {
                return this.sTARTDATEField;
            }
            set {
                this.sTARTDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("END-DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENDDATE {
            get {
                return this.eNDDATEField;
            }
            set {
                this.eNDDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FREQ-TABLE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TT034E00Response_ELIST_UOLACCOUNTSFREQTABLE FREQTABLE {
            get {
                return this.fREQTABLEField;
            }
            set {
                this.fREQTABLEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT034E00")]
    public partial class TT034E00Response_ELIST_UOLACCOUNTSACCOUNTIDX {
        
        private string aCCOUNTIDField;
        
        private string aNNUALELIGIBLEField;
        
        private string aSSESSMENTINDField;
        
        private string fILLERXField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ANNUAL-ELIGIBLE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ANNUALELIGIBLE {
            get {
                return this.aNNUALELIGIBLEField;
            }
            set {
                this.aNNUALELIGIBLEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ASSESSMENT-IND", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ASSESSMENTIND {
            get {
                return this.aSSESSMENTINDField;
            }
            set {
                this.aSSESSMENTINDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FILLER-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FILLERX {
            get {
                return this.fILLERXField;
            }
            set {
                this.fILLERXField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT034E00")]
    public partial class TT034E00Response_ELIST_UOLACCOUNTSFREQTABLE {
        
        private TT034E00Response_ELIST_UOLACCOUNTSFREQTABLEFREQ[] fREQsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("FREQ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public TT034E00Response_ELIST_UOLACCOUNTSFREQTABLEFREQ[] FREQs {
            get {
                return this.fREQsField;
            }
            set {
                this.fREQsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT034E00")]
    public partial class TT034E00Response_ELIST_UOLACCOUNTSFREQTABLEFREQ {
        
        private string fREQCODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FREQ-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FREQCODE {
            get {
                return this.fREQCODEField;
            }
            set {
                this.fREQCODEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CallTT034E00CompletedEventHandler(object sender, CallTT034E00CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallTT034E00CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallTT034E00CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TT034E00Response_SMA Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TT034E00Response_SMA)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TT034E00Response_EREQ _EREQ1 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TT034E00Response_EREQ)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public TT034E00Response_ELIST _ELIST1 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TT034E00Response_ELIST)(this.results[2]));
            }
        }
    }
}

#pragma warning restore 1591