//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18063.
// 
#pragma warning disable 1591

namespace CopRevenueGov2.LCF_RTTIE031_SrvRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TIPSACCTSOAP11Binding", Namespace="http://namespace.softwareag.com/entirex/xml/mapping")]
    public partial class TT031E00 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CallTT031E00OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TT031E00() {
            this.Url = "http://192.168.204.70:10010/wsstack/services/TT031E00.TIPSACCTSOAP11Port/";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallTT031E00CompletedEventHandler CallTT031E00Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("TT031E00", RequestElementName="TT031E00", RequestNamespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT031E00", ResponseElementName="TT031E00Response", ResponseNamespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT031E00", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("_SMA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TT031E00Response_SMA CallTT031E00([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] TT031E00_SMA _SMA, [System.Xml.Serialization.XmlElementAttribute("_E-LCF", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] TT031E00_ELCF _ELCF, [System.Xml.Serialization.XmlElementAttribute("_E-LCF", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out TT031E00Response_ELCF _ELCF1) {
            object[] results = this.Invoke("CallTT031E00", new object[] {
                        _SMA,
                        _ELCF});
            _ELCF1 = ((TT031E00Response_ELCF)(results[1]));
            return ((TT031E00Response_SMA)(results[0]));
        }
        
        /// <remarks/>
        public void CallTT031E00Async(TT031E00_SMA _SMA, TT031E00_ELCF _ELCF) {
            this.CallTT031E00Async(_SMA, _ELCF, null);
        }
        
        /// <remarks/>
        public void CallTT031E00Async(TT031E00_SMA _SMA, TT031E00_ELCF _ELCF, object userState) {
            if ((this.CallTT031E00OperationCompleted == null)) {
                this.CallTT031E00OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallTT031E00OperationCompleted);
            }
            this.InvokeAsync("CallTT031E00", new object[] {
                        _SMA,
                        _ELCF}, this.CallTT031E00OperationCompleted, userState);
        }
        
        private void OnCallTT031E00OperationCompleted(object arg) {
            if ((this.CallTT031E00Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallTT031E00Completed(this, new CallTT031E00CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT031E00")]
    public partial class TT031E00_SMA {
        
        private string _PROGRAMField;
        
        private decimal sYSTEMERRORField;
        
        private bool sYSTEMERRORFieldSpecified;
        
        private decimal eRRORLINEField;
        
        private bool eRRORLINEFieldSpecified;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _PROGRAM {
            get {
                return this._PROGRAMField;
            }
            set {
                this._PROGRAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SYSTEM-ERROR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SYSTEMERROR {
            get {
                return this.sYSTEMERRORField;
            }
            set {
                this.sYSTEMERRORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SYSTEMERRORSpecified {
            get {
                return this.sYSTEMERRORFieldSpecified;
            }
            set {
                this.sYSTEMERRORFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ERROR-LINE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ERRORLINE {
            get {
                return this.eRRORLINEField;
            }
            set {
                this.eRRORLINEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ERRORLINESpecified {
            get {
                return this.eRRORLINEFieldSpecified;
            }
            set {
                this.eRRORLINEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT031E00")]
    public partial class TT031E00_ELCF {
        
        private string aCCOUNTIDField;
        
        private string yEARXField;
        
        private string eSTPAIDXField;
        
        private string yEARField;
        
        private string aMOUNTField;
        
        private string cOMMENTField;
        
        private string yEAR1Field;
        
        private string iNCOME1Field;
        
        private string cOMMENT1Field;
        
        private string yEAR2Field;
        
        private string iNCOME2Field;
        
        private string cOMMENT2Field;
        
        private string yEAR3Field;
        
        private string iNCOME3Field;
        
        private string cOMMENT3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("YEAR-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YEARX {
            get {
                return this.yEARXField;
            }
            set {
                this.yEARXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EST-PAID-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ESTPAIDX {
            get {
                return this.eSTPAIDXField;
            }
            set {
                this.eSTPAIDXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YEAR {
            get {
                return this.yEARField;
            }
            set {
                this.yEARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AMOUNT {
            get {
                return this.aMOUNTField;
            }
            set {
                this.aMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COMMENT {
            get {
                return this.cOMMENTField;
            }
            set {
                this.cOMMENTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("YEAR-1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YEAR1 {
            get {
                return this.yEAR1Field;
            }
            set {
                this.yEAR1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("INCOME-1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INCOME1 {
            get {
                return this.iNCOME1Field;
            }
            set {
                this.iNCOME1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("COMMENT-1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COMMENT1 {
            get {
                return this.cOMMENT1Field;
            }
            set {
                this.cOMMENT1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("YEAR-2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YEAR2 {
            get {
                return this.yEAR2Field;
            }
            set {
                this.yEAR2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("INCOME-2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INCOME2 {
            get {
                return this.iNCOME2Field;
            }
            set {
                this.iNCOME2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("COMMENT-2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COMMENT2 {
            get {
                return this.cOMMENT2Field;
            }
            set {
                this.cOMMENT2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("YEAR-3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YEAR3 {
            get {
                return this.yEAR3Field;
            }
            set {
                this.yEAR3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("INCOME-3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INCOME3 {
            get {
                return this.iNCOME3Field;
            }
            set {
                this.iNCOME3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("COMMENT-3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COMMENT3 {
            get {
                return this.cOMMENT3Field;
            }
            set {
                this.cOMMENT3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT031E00")]
    public partial class TT031E00Response_SMA {
        
        private string _PROGRAMField;
        
        private decimal sYSTEMERRORField;
        
        private bool sYSTEMERRORFieldSpecified;
        
        private decimal eRRORLINEField;
        
        private bool eRRORLINEFieldSpecified;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _PROGRAM {
            get {
                return this._PROGRAMField;
            }
            set {
                this._PROGRAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SYSTEM-ERROR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SYSTEMERROR {
            get {
                return this.sYSTEMERRORField;
            }
            set {
                this.sYSTEMERRORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SYSTEMERRORSpecified {
            get {
                return this.sYSTEMERRORFieldSpecified;
            }
            set {
                this.sYSTEMERRORFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ERROR-LINE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ERRORLINE {
            get {
                return this.eRRORLINEField;
            }
            set {
                this.eRRORLINEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ERRORLINESpecified {
            get {
                return this.eRRORLINEFieldSpecified;
            }
            set {
                this.eRRORLINEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:com-softwareag-entirex-rpc:TIPSACCT-TT031E00")]
    public partial class TT031E00Response_ELCF {
        
        private string aCCOUNTIDField;
        
        private string yEARXField;
        
        private string eSTPAIDXField;
        
        private string yEARField;
        
        private string aMOUNTField;
        
        private string cOMMENTField;
        
        private string yEAR1Field;
        
        private string iNCOME1Field;
        
        private string cOMMENT1Field;
        
        private string yEAR2Field;
        
        private string iNCOME2Field;
        
        private string cOMMENT2Field;
        
        private string yEAR3Field;
        
        private string iNCOME3Field;
        
        private string cOMMENT3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACCOUNT-ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNTID {
            get {
                return this.aCCOUNTIDField;
            }
            set {
                this.aCCOUNTIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("YEAR-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YEARX {
            get {
                return this.yEARXField;
            }
            set {
                this.yEARXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EST-PAID-X", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ESTPAIDX {
            get {
                return this.eSTPAIDXField;
            }
            set {
                this.eSTPAIDXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YEAR {
            get {
                return this.yEARField;
            }
            set {
                this.yEARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AMOUNT {
            get {
                return this.aMOUNTField;
            }
            set {
                this.aMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COMMENT {
            get {
                return this.cOMMENTField;
            }
            set {
                this.cOMMENTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("YEAR-1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YEAR1 {
            get {
                return this.yEAR1Field;
            }
            set {
                this.yEAR1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("INCOME-1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INCOME1 {
            get {
                return this.iNCOME1Field;
            }
            set {
                this.iNCOME1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("COMMENT-1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COMMENT1 {
            get {
                return this.cOMMENT1Field;
            }
            set {
                this.cOMMENT1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("YEAR-2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YEAR2 {
            get {
                return this.yEAR2Field;
            }
            set {
                this.yEAR2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("INCOME-2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INCOME2 {
            get {
                return this.iNCOME2Field;
            }
            set {
                this.iNCOME2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("COMMENT-2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COMMENT2 {
            get {
                return this.cOMMENT2Field;
            }
            set {
                this.cOMMENT2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("YEAR-3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YEAR3 {
            get {
                return this.yEAR3Field;
            }
            set {
                this.yEAR3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("INCOME-3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INCOME3 {
            get {
                return this.iNCOME3Field;
            }
            set {
                this.iNCOME3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("COMMENT-3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COMMENT3 {
            get {
                return this.cOMMENT3Field;
            }
            set {
                this.cOMMENT3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CallTT031E00CompletedEventHandler(object sender, CallTT031E00CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallTT031E00CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallTT031E00CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TT031E00Response_SMA Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TT031E00Response_SMA)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TT031E00Response_ELCF _ELCF1 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TT031E00Response_ELCF)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591